{% set name = "cuequivariance-jax" %}
{% set version = "0.9.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuEquivariance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f68f668ba1a3b3f490d585782c7cd9535a6dcaa08a6d0018f591fb1b762a3e90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./cuequivariance_jax -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cuequivariance
    - jax
    - packaging

test:
  imports:
    - cuequivariance_jax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NVIDIA/cuEquivariance
  summary: CUDA accelerated equivariant operations
  license: Apache-2.0
  license_file: LICENSES/LICENSE

extra:
  recipe-maintainers:
    - fxcoudert
